### ISSUE TITLE
Weblinks don't function anymore

### ISSUE THREAD

**Issue by suriyaa** [ignition-aerospace/ignition-aerospace.github.io#1]
Since we migrated from a static site to Jekyll, the weblinks don't function as expected. You won't get redirected to the destination page after clicking a link or button.

**Comment by SharkyBytes** [comment]
Hey i will help u out...assign it to me

**Comment by suriyaa** [comment]
Thank you very much for your message, @SharkyBytes!

My team and I really appreciate your support. We already managed to fix this bug in commit https://github.com/ignition-aerospace/ignition-aerospace.github.io/commit/24b71af399bc1e14777ba784297c3de69575e8dd by removing `class="smoothscroll"`.

We are happy if you and other GitHub users can contribute to new "good first issue" requests of our projects in the near future.

Looking forward to work together!

All the best,
Suriyaa
*Web Development Lead at Ignition Aerospace*
